layout_spectrum: 0.7522245352456143
typography_spectrum: 1
color:
  lightness: 0.3026844796231293
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  saturation: 0.33105523049490215
  brandStrength: 0.4527139838277777
  rhythmicContrast: 0.4956311231323213
content_rating:
  adult: false
github: true
opengraph: {}
analytics:
  twitter: '@desmonddavidllc'
author:
  name: Paul Larsen
  email: Paul.Larsen@DesmondDavid.com
  url: 'http://www.desmonddavid.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/caaa3bc4-c842-42ce-9e3b-aa54805d036d.png
name: DESMOND DAVID
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e483a76-ff25-4779-9ada-6e3e86c7ebb3.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Desmond David, LLC'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9c55cb4c-c87f-4c90-a242-35323deae6cf.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9c55cb4c-c87f-4c90-a242-35323deae6cf.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'The Social Media, Marketing & Advertising, Digital Strategy Specialists'
purpose:
  - type: contact
    url: 'mailto:Paul.Larsen@DesmondDavid.com'
    label: Contact Us Today!
  - type: internal
    label: About Us!
    item: 5e875e57-fded-4f7d-81c0-fb8993e59fe3
